# -------------------------
# Site identity / basics
# -------------------------
title: "Tranquil Favours"
description: "Aspiring AI/ML Engineer — Python • Data • Models"
url: "https://trvnquil.github.io"
baseurl: ""

# -------------------------
# Author / contact
# -------------------------
author:
  name: "Tranquil Favours"
  email: "iamtranquil02@gmail.com"
  location: "Nairobi, Kenya"
  avatar: "assets/images/profile.jpg"
  linkedin: "https://www.linkedin.com/in/tranquil-omondi/"
  role: "AI/ML Engineer (Student)"

# -------------------------
# Theme and plugins
# -------------------------
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# -------------------------
# Collections (for future projects)
# -------------------------
collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "single-project"

# -------------------------
# Navigation menu
# -------------------------
nav:
  - Home: /
  - Projects: /projects/
  - Blog: /blog/
  - About: /about/

# -------------------------
# Permalink structure
# -------------------------
permalink: /:categories/:year/:title/

# -------------------------
# Excluded files
# -------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
